### ISSUE TITLE
See points for events occurring on a single day

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#1]

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- a circle displays for each single day event and for each multi-day event start day.
- events occurring on the same day do not overlap

**Comment by dschwentker** [comment]
Single day events appear as circles and single day events that occur on the same day are offset vertically so that you can see each circle in all browsers.
