### ISSUE TITLE
Display metadata for a mark on hover

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#10]

**Comment by brittsikora** [comment]
Karen suggested being able to see metadata for all icons on a single timepoint in the case that there are multiple marks for a subject (y) on a single point in time (x)

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- hovering the mouse over a mark reveals a tooltip describing an event

**Comment by dschwentker** [comment]
Hovering on a circle or a line displays tooltips describing the event in all browsers.
