### ISSUE TITLE
Number of participants displayed in header is incorrect 

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#108]
![image](https://user-images.githubusercontent.com/23057086/33785273-4587c584-dc32-11e7-85f1-73e7452678b9.png)

You can see in the screenshot that the number of participants displayed is incorrect in this scenario where I have filtered on both Site 01 and Ongoing = Yes.  The number was correct when I only filtered on Site 01.  This seems to be an issue no matter which site I choose.

When I filter on Site 01 and Ongoing = No the number is still incorrect.  It changes to 1 out of 150 even though there are 24 participant rows displayed.  This seems to be an issue no matter which site I choose.

The same problem exists when I filter on a site combined with the Adverse Event or Concomitant Medications event type filters.  

I produced this bug in the v1.0 code; currently, master in CAT.

**Comment by emmorris** [comment]
Spencer said this was resolved along with #76 in the pull request #79

**Comment by dschwentker** [comment]
Tested and confirmed that the participant numbers/percentages issue appears fixed, compared to what we saw in both v1.0 and v1.1.
