### ISSUE TITLE
Make study_day_range and date_range independent

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#109]
Behaviour is currently somewhat confusing when `study_day_range` is set and `date_range` is not as shown in the screenshots below. 

When the "x-axis scale" control is set to "date" the data is still filtered based on the `study_day_range" setting, but the full axis is shown. Would probably be better to either (1) subset the scale domain or (2) show the full data set in that view. 

![screen shot 2017-12-13 at 6 29 13 am](https://user-images.githubusercontent.com/3680095/33944067-d77cf0ae-dfcf-11e7-9b07-05015111e42f.png)
![screen shot 2017-12-13 at 6 29 33 am](https://user-images.githubusercontent.com/3680095/33944068-d79890fc-dfcf-11e7-9601-068be050cf53.png)

**Comment by jwildfire** [comment]
After talking with @samussiah, proposed solution is to make the ranges fully independent. In the screenshot above, 18 participants will be shown for x-axis scale = "day" while 150 participants will be shown for x-axis scale = "date".

**Comment by dschwentker** [comment]
Tested and confirmed that the study_day_range and date_range are fully independent and can show different sets of participants, depending on how the ranges are set and which X-axis scale is chosen in the Controls.

Used {"study_day_range":[20,50],"date_range":["2016-03-01","2017-03-01"],"filters":[{"value_col":"SITE"}]}
