### ISSUE TITLE
Click row to view linked table

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#11]
UR - "Click row of the timeline to see a detailed view of the clinical events and the underlying data"

- Add ability to navigate back to main chart page

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- detail listing is visible when viewing participant timeline

**Comment by dschwentker** [comment]
Detail listing appears when clicking on a participant link, or selecting a participant from the sorting menu in all browsers.
