### ISSUE TITLE
Annotate Day/Date ranges when showing participant details

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#110]
When viewing participant details, add marks (gray rectangle?) to show the selected range for the current day/date view.

**Comment by samussiah** [comment]
The time range of the ID timeline defaults to the start of that ID's first event and the end of its last event.  Any overlap between the timelines' time range and the ID's time range should be represented by a gray rectangle with a tooltip denoting the timelines' time range.

Test notes:

* Set an initial time range via the Study Day Range or the Date Range and verify that any overlap with an ID's time range is represented by a gray rectangle.

![image](https://user-images.githubusercontent.com/5428548/34573644-d18e2224-f142-11e7-8e37-cb6ab81107c5.png)

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
