### ISSUE TITLE
Can't draw detail view for "hidden" participants

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#111]
If a participant isn't shown on the overview chart, selecting them from the participant view dropdown renders a blank page and throws an error in the console. 
![screen shot 2017-12-13 at 7 02 57 am](https://user-images.githubusercontent.com/3680095/33945378-b4aa4136-dfd3-11e7-86eb-a6f458a4c927.png)

**Comment by dschwentker** [comment]
Tested and confirmed in all browsers that participants not included in the chart due to filtering/range narrowing can still be selected from the participant view list and the participant view is shown without throwing an error.
