### ISSUE TITLE
Make day and date variables optional

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#112]
Chart should be able to be drawn with *either* day or date variables (as specified by user in settings). Having both days and dates is fine, but not required. 

# Test notes
* Confirm that the tools works when there are missing values for either day or date variables
  1. Open "clinical-timeline" using the latest commit from the "optional-timescales" branch and the "testData/ADTIMELINES_partialMissing.csv" dataset. 
  2. Note that there are 10 participants with no "Day" info, and 5 participants with no "Date" info in this data set. 
  3. Confirm that there are 145 participants when x-axis type = Date and 140 when X-axis scale = day.

**Comment by jwildfire** [comment]
Test Notes:  

Confirm that the tools works when there are missing values for either day or date variables

- Open "clinical-timeline" using the latest commit from the "optional-timescales" branch and the "testData/ADTIMELINES_partialMissing.csv" dataset. 
- Note that there are 10 participants with no "Day" info, and 5 participants with no "Date" info in this data set. 
- Confirm that there are 145 participants when x-axis type = Date and 140 when X-axis scale = day.

**Comment by dschwentker** [comment]
Tested and confirmed that chart can be drawn with participants missing either day or date variables. Numbers update as expected, depending on x-axis scale, using the specified dataset.
