### ISSUE TITLE
Y-axis sort and grouping options are different in Firefox only

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#117]
In Firefox the y-axis sort options are "earliest" and "alphabetical-descending,"  Also, the grouping option is in all caps "SITE."

In Chrome and IE sort options are "by earliest event" and "alphanumerically."  The group option is "Site."

I tried clearing cache and the usual things, but the options seemed to stay the same for me in both RhoMAP and CAT.  I marked this as low priority though because the filter still functions and users can grasp the meaning of the options even though they are different.

I found this is the v1.0 version of Clinical Timelines.  

# Test notes
* The options in the dropdowns are identical across browsers.

**Comment by danedexF5** [comment]
@samussiah naming is consistent across the browsers but I do not see a Grouping option

**Comment by samussiah** [comment]
@danedexF5 you'll need to add a grouping:

![image](https://user-images.githubusercontent.com/5428548/41422997-393038a0-6fc8-11e8-9d8b-2f4757262201.png)

**Comment by danedexF5** [comment]
Ok, all good
