### ISSUE TITLE
Changing x-axis scale throws error if no day/date info is available for participant

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#128]
Currently users can toggle to an x-axis scale with missing data in participant view. To reproduce bug: 

- Use the v1.2-dev branch and the "testData/ADTIMELINES_partialMissing.csv" dataset. 
- Select 01-010 participant view
- Change X-axis scale to "date" and observe the console error below: 

<img width="478" alt="screen shot 2018-01-10 at 7 58 10 am" src="https://user-images.githubusercontent.com/3680095/34781943-0bbb730a-f5dc-11e7-90a8-ac9a8fcf0b92.png">

# Test notes
* No error is thrown when the time scale is toggled in the ID timeline view regardless of whether that ID is missing data for one or both time scales.
  1. In CAT, load _testData/ADTIMELINES\_partialMissing.csv_
  2. Navigate to the ID timeline view.
  3. Find an ID with only day or only date data.
  4. Switch the time scale.
  5. Verify no errors are thrown.

**Comment by jwildfire** [comment]
Test Notes: Follow the steps in the issue description and confirm that the error shown *does not* appear in the log.

**Comment by dschwentker** [comment]
Tested and confirmed in all browsers that toggling to an x-axis in the participant view where the participant is missing that data scale does not throw an error in the console, and it displays the "No data selected" message in the table and shows no charts.
