### ISSUE TITLE
Hide x-axis toggle if there is no day (or date) variable in the data

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#129]
Confirm that we can draw a clinical-timeline with only one x-axis type. Use ADTIMELINES_noDays.csv - which only has date information, but not day information, in CAT to confirm. X-axis scale control should be hidden in this use case. 

# Test notes
* The _X-axis scale_ control does not appear if only dates or days are provided.
  1. In CAT, load _testData/ADTIMELINES_noDays.csv_
  2. Verify the x-axis scale control is not displayed.

**Comment by jwildfire** [comment]
Test notes: Confirm that no x-axis time scale is visible when loading ADTIMELINES_noDays.csv in the latest build of clinical-timelines in CAT.

**Comment by dschwentker** [comment]
Tested and confirmed that the x-axis control is hidden when using a dataset that only has date information, but no day information. Passed in all browsers.
