### ISSUE TITLE
Add vertical line on x-axis during creation

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#13]
Input from Karen B

Spencer: "vertical line can be handled with a custom option like (pseudo-code) referenceLine: {studyDay: 28)"

**Comment by emmorris** [comment]
Array of reference lines

**Comment by jwildfire** [comment]
Test Notes: Test in CAT using: `{"referenceLines":[{"studyDay":100,"label":"More than 99"},150]}`

**Comment by mhickle** [comment]
Pass

![1](https://user-images.githubusercontent.com/31038805/32176044-f6ac2aca-bd5c-11e7-8e58-3d5c1a85f908.PNG)
