### ISSUE TITLE
Participants who have day info, but not date info, don't appear in participant dropdown

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#131]
As shown below for participants 01-011 through 01-015 in ADTIMELINES_PartialMissing.csv

<img width="1056" alt="screen shot 2018-01-16 at 7 37 11 am" src="https://user-images.githubusercontent.com/3680095/34996995-1a66144c-fa90-11e7-89f0-6f7b0c42267e.png">

# Test notes
* All participants should appear in the ID dropdown regardless of the current time scale.

**Comment by jwildfire** [comment]
Test Notes: Confirm that all ID with missing day or date info are included in the Participant drop down. In particular, 01-011 through 01-015 in ADTIMELINES_PartialMissing.csv should be visible in the dropdown.

**Comment by dschwentker** [comment]
Tested and confirmed that all participant IDs are included in the Participant dropdown, even if they have missing day or date info and are not shown in the chart view, depending on the X-axis scale selection.
