### ISSUE TITLE
Add background rect to grouping annotations.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#133]
in _horizontally.js_:

```
                        textArea = annotation.node().getBBox(),
                        background = g
                            .insert('rect', ':first-child')
                            .attr({
                                x: textArea.x,
                                y: textArea.y,
                                width: textArea.width,
                                height: textArea.height,
                                fill: 'white'
                            }),
```

# Test notes
* Horizontal group annotations have a white background.
* Reference lines that overlap horizontal grouping annotations are not visible behind the horizontal grouping annotations.
* Example settings object: `{groupings: ['RACE'], grouping_initial: 'RACE', reference_lines: ['2015-02-07']}`

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
