### ISSUE TITLE
Add a frequency table of events at each reference line.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#134]
Addressed in [`reference_line_tables`](https://github.com/RhoInc/clinical-timelines/tree/reference-line-tables).

# Test notes
* For each reference line a corresponding frequency table appears in the left column beneath the controls.
* The title of the frequency table matches the reference line tooltip.
* The frequency table breaks down the events that overlap the reference line by event type, and if the timelines are grouped, by the group variable.

Use settings below:  
```
{
  "groupings":[
    {"value_col":"SEX","label":"sex"}
  ],
  "reference_lines":[
    {"timepoint":"2015-05-01","label":"timepoint"}
  ]
}
```

**Comment by dschwentker** [comment]
This has been tested and passed in all browsers.
