### ISSUE TITLE
Ability to control the order the symbols appear in the legend during creation

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#14]
Input from Karen B

Spencer: "we'd need either a setting that dictates the symbol order or a data-driven symbol code that sorts them"

**Comment by samussiah** [comment]
`config.eventTypes` is a setting that expects an array of strings that dictates the order of the events as well as which events appear in the initial view.

**Comment by samussiah** [comment]
Test notes:

- Specifiying a list of event types in `config.eventTypes` results in the renderer filtered on those event types and those event types appear first in the legend.

**Comment by samussiah** [comment]
Added an issue to define a JSON schema so we can get this renderer in CAT.

**Comment by dschwentker** [comment]
Tested and passed in all browsers
