### ISSUE TITLE
Have flexibility in the symbols used for different events during creation

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#15]
Input from Karen B

Spencer: "it'd have to be data driven"

**Comment by jwildfire** [comment]
Initial implementation = drop down with a list of events. When event is selected it gets `.emphasis` class with extra stroke-width etc.

**Comment by mhickle** [comment]
Pass

![3](https://user-images.githubusercontent.com/31038805/32176184-53ccd5ec-bd5d-11e7-856e-1b152b975ff2.PNG)

**Comment by samussiah** [comment]
Test notes:

* Each event type has a distinct color.
* The user can highlight any one event type and it receives a bold, black outline.
