### ISSUE TITLE
Hide Y-axis grouping control if no groups are available

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#153]
![screen shot 2018-01-27 at 7 44 54 am](https://user-images.githubusercontent.com/3680095/35473486-152b0164-0336-11e8-9f87-cc63bca0f396.png)

# Test notes
* When no groupings are specified in the settings the _Y-axis grouping_ control does not appear: `{groupings: null}`.
* Otherwise the control appears: `{groupings: ['AGE']}`.

**Comment by dschwentker** [comment]
Getting some pretty odd behavior trying to test this. In both Firefox and Chrome, when I add groupings, the Y-axis grouping filter still does not appear in the Controls section.

In IE, the chart does not even render if I do not add groupings, though I don't see any error shown. However, when I do add groupings, it renders and actually shows the Y-axis grouping control option.

**Comment by dschwentker** [comment]
Tested and passed in all browsers - y-axis grouping is hidden by default, but can be added via form or text settings.
