### ISSUE TITLE
Ability to label pre-selected variables available for item grouping

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#16]
Input from Karen B

Spencer: "label groups can be handled via webCharts.multiply() on cohort or treatment group or however they want to group the timelines"

**Comment by emmorris** [comment]
Maybe a duplicate of #6?  Britt will confirm with Karen and Brian.

**Comment by brittsikora** [comment]
This is a confirmed to be a duplicate of #6
