### ISSUE TITLE
Allow data-driven mark offset.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#166]
for circles:
```
        this.svg.selectAll('g.point')
            .each(function(d) {
                d3.select(this)
                    .attr('transform', 'translate(0,' + (+d.values.raw[0].offset * +mark.radius * 2) + ')');
            });
```
for lines:
```
        this.svg.selectAll('g.line')
            .each(function(d) {
                d3.select(this)
                    .attr('transform', 'translate(0,' + (+d.values[0].values.raw[0].offset * +mark.attributes['stroke-width'] * 1.5) + ')');
            });
```
`offset_col = null` by default

# Test notes
* Set `offset_col` to _OFFSET_.  Each mark should be offset vertically by a factor of the _OFFSET_ variable in ADTIMELINES.

**Comment by danedexF5** [comment]
@samussiah so 2 things.
- I am not noticing any change when I add offset_col: OFFSET to the json block. What should be changing exactly?
- For some reason, Chrome isn't rendering the same as IE and FF.

**Comment by samussiah** [comment]
@danedexF5 , with `offset_col` set to _OFFSET_, _Enrollment_, _Randomization_, and _Study Completion_ should appear on the same level vertically, _Adverse Events_ should offset to their own level, and _Concomitant Medications_ should offset to their own level.  When `offset_col` is not defined the events should offset dynamically so lines don't overlap with other lines and circles don't overlap with other circles.

**Comment by danedexF5** [comment]
@samussiah I still wasn't getting any difference when I used mark-offset-setting so I used the latest commit bf65c1fe3d8f128b2ac07b9dd621b32a5d02de85 and now offset_col: OFFSET gets the expected result as you described. When I don't have it set I do get overlap of lines though.

**Comment by samussiah** [comment]
As long as you're seeing an offset tied to the even type, it's good to go.  For instance, this overlap is expected (though not optimal; it'd be nice to fit the bands to the number of overlapping events):
![image](https://user-images.githubusercontent.com/5428548/40241371-dfc10b7c-5a88-11e8-96c6-7a3c8307d02b.png)
It's just that _02-010_ has more overlapping events than will fit their vertical space, which can be fixed by increasing the `range_band` and/or reducing the `mark_thickness`.

**Comment by danedexF5** [comment]
@samussiah tried this in all 3, Offset is working as expected and I did switch mark_thickness to a lower number and the lines separated(no overlap) as expected.
