### ISSUE TITLE
Define data spec

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#17]
One record per event

Maybe use the AE standards

Create data spec wiki

**Comment by samussiah** [comment]
Data should be one record per event with these columns:

- `id_col`: _USUBJID_
- `event_col`: _DOMAIN_
- `seq_col`: _SEQ_
- `stdy_col`: _STDY_
- `endy_col`: _ENDY_

**Comment by jwildfire** [comment]
Copied comment above to wiki
