### ISSUE TITLE
Migrate code from AE Timeline

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#18]
Put AE timeline code in this repo and update the configs to match new data spec.

**Comment by samussiah** [comment]
Test notes:

* clinical-timelines has the same basic functionality as ae-timelines

**Comment by samussiah** [comment]
Test notes:

- clinical-timelines has the same basic functionality as ae-timelines

**Comment by dschwentker** [comment]
cinical-timelines looks good to in Chrome and Firefox, but I can't get it to render in IE 11.
