### ISSUE TITLE
Figure out how to handle ongoing events

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#19]

**Comment by jwildfire** [comment]
Jeremy to work on data spec for censoring

**Comment by emmorris** [comment]
This was requested during the Oct 16 demo with Karen K., Karen B., Brian A., and David H.

**Comment by samussiah** [comment]
Test notes:

* Ongoing events (records where `ongo_col` equals `ongo_val`) are capped at the end/on the right side with a symbol.

**Comment by dschwentker** [comment]
Ongoing event symbols confirmed in all browsers.
