### ISSUE TITLE
Add highlighting for triangles, squares, and diamonds.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#193]
# Test notes
* Custom marks (triangle, squares, diamonds) can be highlit.

**Comment by danedexF5** [comment]
@samussiah I am only seeing arrows and I cannot highlight

**Comment by samussiah** [comment]
@danedexF5 would you post a screenshot?  I'm seeing this:

![image](https://user-images.githubusercontent.com/5428548/41423125-7b6edaa0-6fc8-11e8-8d19-ef2f4399acf4.png)

vs

![image](https://user-images.githubusercontent.com/5428548/41423151-8c437e26-6fc8-11e8-8557-05ec156490a4.png)

Circles and lines should function as before, black on the inside with a colored border/stroke.

**Comment by danedexF5** [comment]
@samussiah Ah ok. Didn't know about changing those settings. The highlighting is working then. One thing I did notice and not sure if this is by design or not. I used Concomitant Medications as the Event and have tried a few different symbols, no change. It does highlight though.
