### ISSUE TITLE
Deal with overlapping points

### ISSUE THREAD

**Issue by emmorris** [RhoInc/clinical-timelines#20]

**Comment by samussiah** [comment]
In progress.  Points are dealt with; lines are more difficult.

**Comment by samussiah** [comment]
Test notes:

- Single day events that occurred on the same day are offset from each other.
- Multiday events with any overlap are offset from each other.

**Comment by dschwentker** [comment]
Same day events and overlapping multiday event lines both appear offset in all browsers.
