### ISSUE TITLE
Make option for table config

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#21]
Let user pass a valid config object for the webcharts table in the detail view.

**Comment by samussiah** [comment]
Test notes:

* Passing a valid `webcharts.createTable()` settings object to `listingConfig` affects the participant detial listing, e.g.:

```javascript
{"listingConfig": {
    "searchable": true,
    "sortable": true,
    "pagination": false,
    "exportable": false
}}
```

**Comment by jwildfire** [comment]
@samussiah config seems to work pretty well at showing/hiding the extra table components, but the actual table isn't rendering ;) 
<img width="1328" alt="screen shot 2017-10-31 at 7 39 28 am" src="https://user-images.githubusercontent.com/3680095/32229772-dd68a8ce-be0e-11e7-9862-6cdb597ac692.png">

**Comment by jwildfire** [comment]
Most likely an easy-ish fix [here](https://github.com/RhoInc/clinical-timelines/pull/32/files#r148017459)

**Comment by dschwentker** [comment]
Tested and confirmed can toggle listingConfig controls to turn on and off search, sorting, pagination, and exporting of the table on the participant detail listings in all browsers.
