### ISSUE TITLE
Let user specify detail columns

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#23]
The specified columns should appear in the summary table

**Comment by emmorris** [comment]
This was requested during the Oct 16 demo with Karen K., Karen B., Brian A., and David H.

**Comment by samussiah** [comment]
Test notes:

* Specifying an array of variable names dictates the columns presented in the participant detail listing, e.g.:
```javascript
{"details": ["RFSTDTC", "ARM", "SEX"]}
```
* Specifying an array of objects with `value_col` and `label` properties dictates the columns and column headers presented in the participant detail listing, e.g.:
```javascript
{"details": [
    {"value_col": "RFSTDTC", "label": "Reference Start Date"},
    {"value_col": "ARM", "label": "Treatment Group"},
    {"value_col": "SEX", "label": "Sex"}
]}
```

**Comment by jwildfire** [comment]
@samussiah Array of character isn't working - Array of objects looks good.

**Comment by dschwentker** [comment]
Tested and confirmed arrays to add new columns, with and without custom labels, in all browsers.
