### ISSUE TITLE
Add demographics summary to participant view

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#24]
User specified `demog_cols` are printed on details view (values from first row of matching data set shown)

**Comment by emmorris** [comment]
This was requested during the Oct 16 demo with Karen K., Karen B., Brian A., and David H.

**Comment by samussiah** [comment]
Test notes:

* Specifying an array of variable names dictates the columns presented in the participant details in the controls section, e.g.:
```javascript
{"id_characteristics": ["RFSTDTC", "ARM", "SEX"]}
```
* Specifying an array of objects with `value_col` and `label` properties dictates the participant details and detail labels in the controls section, e.g.:
```javascript
{"id_characteristics": [
    {"value_col": "RFSTDTC", "label": "Reference Start Date"},
    {"value_col": "ARM", "label": "Treatment Group"},
    {"value_col": "SEX", "label": "Sex"}
]}
```

**Comment by jwildfire** [comment]
@sammusiah the array of string isn't working in latest 0.2-dev build.  (array of objects works as expected). 

![screen shot 2017-10-31 at 7 18 53 am](https://user-images.githubusercontent.com/3680095/32228600-eb78d914-be0b-11e7-9667-e1b842adad68.png)

**Comment by dschwentker** [comment]
Tested and confirmed arrays to add new participant details in the controls section, with and without custom labels, in all browsers.
