### ISSUE TITLE
Click legend to filter

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#25]

**Comment by mhickle** [comment]
Pass

![2](https://user-images.githubusercontent.com/31038805/32176077-08fd019a-bd5d-11e7-9127-4ec9fbfc7b94.PNG)

**Comment by samussiah** [comment]
Test notes:

* Clicking a legend item with a gray background removes that event type from the chart.
* Clicking a legend item with a white background adds that event type to the chart.
* Clicking a legend item updates the event type filter accordingly.
* The participant timeline only displays those events that aren't currently filtered out.
