### ISSUE TITLE
Add JSON schema.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#28]

**Comment by samussiah** [comment]
Test notes:

* `settings-schema.json` contains an object for each renderer-specific setting in the `src/defaults/settings`.
* The [charting application tester](https://rhoinc.github.io/CAT/) presents a form with fields corresponding to each renderer-specific setting.

**Comment by dschwentker** [comment]
Confirmed that clinical-timelines shows a form in the CAT with fields corresponding to the settings given in src/defaults/settings.js.
