### ISSUE TITLE
View a legend that identifies the marks (points and lines) used in the chart

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#3]
Also add ability to plot multiple unique marks for corresponding clinical data points

**Comment by jwildfire** [comment]
Not sure there's much to do here - just add support for #15

**Comment by mhickle** [comment]
Pass

![3](https://user-images.githubusercontent.com/31038805/32176149-40d980ac-bd5d-11e7-977e-acef1126abaf.PNG)

**Comment by samussiah** [comment]
Test notes:

* A legend appears at the top of the chart with a legend item for each event type present in the data.
