### ISSUE TITLE
See the number and percentage of rows displayed in the current view

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#4]
Just like on our other charts; it should update with each user interaction

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- in cumulative view population stats are visible in the top right corner of the controls container
- in participant view participant information is visible in the top right corner of the controls container

**Comment by dschwentker** [comment]
Population stats and participant information are appearing as expected in the top right of the controls container in all browsers.
