### ISSUE TITLE
Make `ongo_col`optional

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#41]
If user specifies ongoing column as null, then assume that no lines are ongoing.

**Comment by jwildfire** [comment]
Test Notes: 
- Render chart in CAT using `"ongo_col":null` and confirm that no arrows are drawn
- Arrows should still be shown by default, since default value for `ongo_col` setting is unchanged.

**Comment by mhickle** [comment]
Pass

![4](https://user-images.githubusercontent.com/31038805/32513819-3d6bd510-c3c9-11e7-988b-f7cca1a37c7d.PNG)
![5](https://user-images.githubusercontent.com/31038805/32513820-3d786028-c3c9-11e7-93e9-6689d10abcc8.PNG)
