### ISSUE TITLE
Allow user to specify a custom data-driven tooltip.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#44]

**Comment by jwildfire** [comment]
Testing notes:
- Confirm that custom tooltips appear on mouseover by default. 
- Change the "tooltip_col" setting in CAT to another variable (e.g. "STDY") and confirm that that variable is shown instead.

**Comment by mhickle** [comment]
Pass

![7](https://user-images.githubusercontent.com/31038805/32514069-e735c380-c3c9-11e7-888e-9514a51f49c3.PNG)
