### ISSUE TITLE
Toggle the x-axis to display different time measures 

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#5]
(e.g. study day, visit, or visit number)

**Comment by emmorris** [comment]
Covered by #18

**Comment by emmorris** [comment]
Need to think about what we want defaults to be.

**Comment by jwildfire** [comment]
We might not want to do this ...

**Comment by jwildfire** [comment]
- Consider adding 2nd axis showing date when looking at a single participant
- Make prevalent with mouseover

**Comment by samussiah** [comment]
not unprecedented; check out project 259

**Comment by dschwentker** [comment]
Confirmed that I can toggle the x-axis between Study Day and Date in all browsers.
