### ISSUE TITLE
Make marks more prominent.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#51]
#167 also addresses this issue.

# Test notes
* Verify that timepoints (circles, triangles, squares, diamonds) are outlined in black.

**Comment by samussiah** [comment]
But honestly highlighting is pretty darn prominent.  Maybe two types of highlighting.

**Comment by brittsikora** [comment]
Do we need this?

**Comment by samussiah** [comment]
I think perhaps allowing the user to specify the thickness of the lines and the radius of the circles would be useful.  Not pressing because the user can zoom in on the timelines, refresh, and have thicker marks.
