### ISSUE TITLE
ReadMe Images

### ISSUE THREAD

**Issue by mhickle** [RhoInc/clinical-timelines#56]

**Comment by mhickle** [comment]
![ctlgif](https://user-images.githubusercontent.com/31038805/32514368-ccf98744-c3ca-11e7-890d-d10bba8350ff.gif)

**Comment by mhickle** [comment]
![gif2](https://user-images.githubusercontent.com/31038805/32564160-551d89b6-c481-11e7-926e-d124bfdebe40.gif)

**Comment by mhickle** [comment]
![ezgif com-crop](https://user-images.githubusercontent.com/31038805/32564347-00fbfcea-c482-11e7-85ce-1379751ede62.gif)

**Comment by mhickle** [comment]
![gif3](https://user-images.githubusercontent.com/31038805/32564699-14931e54-c483-11e7-82bb-43e448ad6ada.gif)

**Comment by mhickle** [comment]
![gif3](https://user-images.githubusercontent.com/31038805/32617020-e0ba4ac0-c541-11e7-86e4-1cf5ba30f61d.gif)

**Comment by mhickle** [comment]
![4](https://user-images.githubusercontent.com/31038805/32617032-e90cc4aa-c541-11e7-8ec8-c8867de51c94.PNG)

**Comment by emmorris** [comment]
No development or testing involved.  Just a placeholder issue for images.
