### ISSUE TITLE
Revisit display of controls in ID timeline view.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#59]
For example hide rather than disable controls that don't make sense in the ID timeline view such as ID-level filters, y-axis sorting, and y-axis grouping.

**Comment by samussiah** [comment]
Staying with disabled controls, and controls have been re-ordered so that controls that affect both views are positioned first.

**Comment by jwildfire** [comment]
Still thinking we should move to hidden controls, as discussed.

**Comment by samussiah** [comment]
Test notes:

* Verify that all controls except the ID view, event highlighting, x-axis scale, and event type filter are hidden in the ID view.

**Comment by dschwentker** [comment]
Tested and confirmed that in the single Participant view, the only visible, default controls are Participant view, Event highlighting, and X-axis scale and the only Filter is Event Type.
