### ISSUE TITLE
Group items on the y-axis using a pre-selected variable

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#6]
We need to decide what variables we want to use

**Comment by emmorris** [comment]
May use webcharts.multiply to group.

**Comment by emmorris** [comment]
This was requested during the Oct 16 demo with Karen K., Karen B., Brian A., and David H.  The grouping is very important for open label studies.

**Comment by samussiah** [comment]
Test notes:

- Site appears in Y-axis grouping dropdown.
- Any `id_characteristics` variables appear in Y-axis grouping dropdown.
- IDs are grouped by corresponding variable in Y-axis grouping dropdown and sorted within each group according to the Y-axis sort dropdown.

**Comment by samussiah** [comment]
With horizontal grouping consider printing groups on both the left and right side of the timelines, or print the group once in the middle.

**Comment by jwildfire** [comment]
I think it's fine to leave the `groupings` variable for now. Doesn't hurt to keep it separate from ID variables.

**Comment by mhickle** [comment]
Pass

![6](https://user-images.githubusercontent.com/31038805/32513971-aa097038-c3c9-11e7-8a4c-3e5e572440c6.PNG)
