### ISSUE TITLE
Add site filter

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#7]
Corresponds to the following UR - "Change the input on the site filter, and see an updated chart"

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- renderer contains a site filter by default

**Comment by dschwentker** [comment]
Site filter is working in all browsers when filtered on Participant = All, and the filter is disabled when filtered to one particular participant.
