### ISSUE TITLE
Allow user to specify a study day and/or a date range.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#73]
* `study_day_range`: two-item array of start and end days
* `date_range`: two-item array of start and end dates, either `Date`s or strings whose format matches `settings.date_format`

**Comment by jwildfire** [comment]
Test Notes: Confirm that modifying the options specified above change the x-axis as expected. IDs with no values in the given range should be hidden, with a note given in the "population count" div in the upper left hand corner.

**Comment by dschwentker** [comment]
Confirmed that both the study_day_range and date_range can be modified independently to change the x-axis as expected, depending on which X-axis scale control option you select. The population count numbers appear correct based on the study_day_range or date_range filters, along with other chosen filters.

Used {"study_day_range":[20,50],"date_range":["2016-03-01","2017-03-01"],"filters":[{"value_col":"SITE"}]}
