### ISSUE TITLE
Add time range controls.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#74]
# Test notes
* A Start and End control appear in the controls section.
* The controls display a date set to the current time range.
* Given a date x-axis scale the controls display a date.
* Given a day x-axis scale the controls display a number.
* The controls accept text input and may contain up and down arrows that increment or decrement the time range.
* The Start control cannot be greater than the End control, and vice versa.

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
