### ISSUE TITLE
Remove IDs with no events in the specified time range.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#75]

**Comment by samussiah** [comment]
Or add a checkbox to unhide them.

**Comment by jwildfire** [comment]
Test Notes: Confirm that only a subset of the participants are shown in the chart when using a small subset of dates such as `{"study_day_range":[10,20]}`. The counts in the top right corner should match the data shown.

**Comment by dschwentker** [comment]
Tested and confirmed that participant numbers and percentages appear correct when filtering and changing views. Changing date_range or study_date_range filters causes the displayed and hidden numbers and percentages to appear and the values shown appear correct based on the filters. Confirmed that filtering on events updated the numbers as expected as well.
