### ISSUE TITLE
Calculate sample count (out of population count) from something other than `chart.filtered_data`.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#76]
Because `chart.filtered_data` might not represent only the filters applied to `chart.raw_data` but also the filters applied within a mark by the `values` property.

**Comment by jwildfire** [comment]
Test Notes: Confirm that the values in the top right corner update as expected when filtering and changing views. The following settings can be used as a baseline for testing: `{"study_day_range":[10,50],"filters":[{"value_col":"SITE"}]}`

**Comment by dschwentker** [comment]
Tested and confirmed that participant numbers and percentages appear correct when filtering and changing views. Changing date_range or study_date_range filters causes the displayed and hidden numbers and percentages to appear and the values shown appear correct based on the filters.
