### ISSUE TITLE
Add support for series of reference lines

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#85]
e.g. 1st of every month, or every 50 days.

Suggested by @agstn

Went with a tooltip that shows where the mouse is.

# Test notes
* Hovering anywhere other than over a mark displays a tooltip with the x-position of the mouse.

**Comment by dschwentker** [comment]
Only works intermittently in Firefox, but works consistently in Chrome and IE. Per Spencer, it's good enough to pass.
