### ISSUE TITLE
Minor refactor of "highlight" style

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#87]
Be consistent with how we handle highlighting styles between lines and points. Currently we have: 
- Points
  - not highlighted = colored stroke, white fill
  - highlighted = black stroke,  colored fill
- lines
  - not highlighted = no stroke, colored fill
  - highlighted = black stroke (well, pseudo-stroke), colored fill.

I propose the following for both lines and points: 
- Not highlighted = colored fill , no stroke 
- highlighted = optional fill based on config.highlight_color (default:white), colored stroke

**Comment by jwildfire** [comment]
Test Notes: Went with black stroke and a fill controlled by `event_highlight_color`. Test with these settings (change color to confirm functionality): 
```
{"event_highlight_color":"yellow"}
```

**Comment by dschwentker** [comment]
Tested and confirmed that the highlight color can be changed from black to other colors by updating {"event_highlight_color":"yellow"}
