### ISSUE TITLE
Remove site_col config option

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/clinical-timelines#88]
"site" variable can just be specified in `groupings` and`filters` options as desired.

**Comment by jwildfire** [comment]
One place that will need an update: https://github.com/RhoInc/clinical-timelines/pull/68#discussion_r150948000

**Comment by jwildfire** [comment]
Test Notes: Confirm that a site filter no longer appears by default, but can be added via `{"filters":[{"value_col":"SITE","label":"Site"}]}`

**Comment by dschwentker** [comment]
Confirmed that the site filter does not appear by default, but it can be added to the filters of the chart manually in all browsers.
