### ISSUE TITLE
Sort rows by the earliest occurring event or alphabetical/descending order

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/clinical-timelines#9]

**Comment by emmorris** [comment]
Covered by #18

**Comment by samussiah** [comment]
Test notes:

- _Sort participants_ control in controls container contains two options:
  - _by earliest event_
  - _alphanumerically_
- _by earliest event_ sorts y-axis by each participant's earliest event
- _alphanumerically_ sorts y-axis by participant ID

**Comment by dschwentker** [comment]
Earliest event and alphanumerically sorting both work as described in all browsers.
