### ISSUE TITLE
Can Only Sort Y-Axis Once

### ISSUE THREAD

**Issue by mhickle** [RhoInc/clinical-timelines#91]
When highlight is active you cannot sort the Y-Axis (issue #89), but with no highlighting the user can only sort the Y-Axis once.

**Comment by samussiah** [comment]
@mhickle , would you retry this scenario without the Enrollment event type displayed?  Every ID's Enrollment event occurs on day 1 so the sort will always be alphanumeric even if sorting by earliest event.

**Comment by mhickle** [comment]
Great! Now its working
