### ISSUE TITLE
Styling Issues for Participant View 

### ISSUE THREAD

**Issue by mhickle** [RhoInc/clinical-timelines#95]
The participant view in IE looks like this:
![11](https://user-images.githubusercontent.com/31038805/32908252-01df612e-cad1-11e7-873c-d175f9af9de4.PNG)

**Comment by jwildfire** [comment]
Might be ok to ignore this bug if it is IE only since layout is refactored in v1.1 ...

**Comment by samussiah** [comment]
Turned `resizable` back to `false`.  Required to compute the size of the multiples correctly.
