### ISSUE TITLE
Exportable Setting not working 

### ISSUE THREAD

**Issue by mhickle** [RhoInc/clinical-timelines#97]
I am still able to export the CSV with the following settings:

{"listingConfig":{"searchable":false,"sortable":false,"pagination":false,"exportable":false}}
 
![12](https://user-images.githubusercontent.com/31038805/32909197-f33a35ba-cad3-11e7-9165-29f3cbb87d95.PNG)

**Comment by samussiah** [comment]
Sorry @mhickle , I updated that the setting name from `listingConfig` to `details_config`.  Try the latter if you would.

**Comment by mhickle** [comment]
Im still able to download it 
![14](https://user-images.githubusercontent.com/31038805/32912781-175347b6-cade-11e7-9999-ec3cdcdea8d6.PNG)
