### ISSUE TITLE
Line offsets break when event types are removed.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/clinical-timelines#99]

**Comment by samussiah** [comment]
Removing and re-adding time intervals throws the offsets out of sync:

Initial:
![image](https://user-images.githubusercontent.com/5428548/34047993-0f76c1ae-e180-11e7-9daf-c05801646dc7.png)

Removing CMs:
![image](https://user-images.githubusercontent.com/5428548/34048006-1ed08978-e180-11e7-8459-d78e428ab278.png)

Re-adding CMs:
![image](https://user-images.githubusercontent.com/5428548/34048036-34679452-e180-11e7-9ff4-be05a6a8e0a7.png)

Test notes:
* Lines representing overlapping time intervals are always adjacent vertically.
* Lines representing overlapping time intervals are never overlapping.
* Any set of event types yields a an unchanging set of line offsets, regardless of the previous set of event types.

**Comment by dschwentker** [comment]
Tested and passed in all browsers.
